/* Bilingual presentation layer. Student answers remain in their original language. */
const $ = id => document.getElementById(id);
const elementKeys = ["process", "knowledge", "problem", "solution", "reflection", "outcome"];
const copy = {
  zh: {
    heroTitle: "英国本科 CS 顾问工作台",
    heroDescription: "顾问先看学生已有材料，再通过追问补足过程与思考。未确认的信息保留为空。",
    stepIntro: "01 · 建立案例", introDescription: "选择英国本科 CS 项目，再上传结构化、已脱敏的 CV JSON。每次处理一段经历，进行三轮追问。",
    programLabel: "目标项目", programNote: "项目要求摘自原系统，尚未人工核实；UCAS 通用写作指引与学校要求分开展示。", guidanceTitle: "UCAS 通用文书指引", guidanceScope: "这是英国通用指引，不是目标学校的专属招生偏好。", guidanceLink: "查看 UCAS 来源",
    cvLabel: "结构化 CV（.json）", chooseFile: "选择 JSON 文件", noFile: "尚未选择文件", downloadSample: "下载示例 CV，修改后用于测试", startUploaded: "使用上传的 CV 开始", start: "试用内置案例",
    uploadNote: "请使用虚构或已脱敏的数据。文件只发给本地服务，并在服务重启后从内存清除。",
    fileMissing: "请先选择 JSON 文件。", fileLarge: "CV 文件不能超过 25 KB。", fileInvalid: "文件不是有效的 JSON。",
    stepInterview: "02 · 定向追问", answerLabel: "学生的原话",
    answerPlaceholder: "尽量写具体：发生了什么、你自己做了什么、为什么这样做。",
    submit: "提交回答", skip: "跳过这题", finishEarly: "现在生成素材卡", recordTitle: "六要素记录",
    stepResult: "03 · 顾问审阅", restart: "重新开始",
    footer: "课程原型。仅上传虚构或已脱敏 CV；院校要求尚未人工核对。不是录取判断或个人陈述成稿。",
    empty: "尚未获得", unanswered: "未回答／未确认", evidenceTitle: "已确认的学生证据",
    angleTitle: "写作角度（待顾问确认）", gapsTitle: "项目要求与待核对差距",
    modeLive: "DashScope 模型生成，证据引文已逐字校验", modeDemo: "本地模板演示；未调用模型",
    gapNote: "要求库 human_verified=false；演示仅展示比对逻辑，请顾问访问官网重新核对。",
    noGaps: "当前结构化成绩未触发所选示例要求的差距；仍需核对官网和完整申请条件。", subjectsPrefix: "预估科目：",
    sourceLink: "打开目标项目官网", quotePrefix: "逐字证据：", missingPrefix: "仍需补充：",
    notice: "写作角度仅供顾问与学生讨论；不得把未确认的推测写成学生经历。院校要求尚未人工核对。",
    needsEvidence: "待补充证据", reviewable: "可供顾问审阅", completeness: "六要素",
    student: "虚构学生 A（高二，A-Level）", experience: "校数学建模社团，参与市级中学生数学建模竞赛",
    questionProblem: "在这段经历中，你亲自遇到的一个具体困难是什么？当时卡在哪里？",
    questionSolution: "针对刚才的困难，你尝试了什么方法？你自己做了哪一步，为什么这样做？",
    questionReflection: "这段经历让你对申请专业产生了什么新疑问或思考？如果没有，也可以直接说没有。",
    gapMath: (actual, expected) => `Mathematics 预估 ${actual || "未知"}；示例要求为 ${expected}。`,
    gapScience: "目前档案未列出示例要求中的任一门科学科目。",
    usage: (input, output) => `本次调用：输入 ${input} tokens，输出 ${output} tokens。`,
    labels: {process:"行为过程",knowledge:"运用知识",problem:"遇到的问题",solution:"解决方法",reflection:"个人思考",outcome:"最终收获"},
    facts: {"担任数据整理与图表制作":"担任数据整理与图表制作","数据整理、图表制作":"数据整理、图表制作","市级三等奖":"市级三等奖"},
    errorFallback: "请求失败，请查看服务端日志。"
  },
  en: {
    heroTitle: "A focused workbench for UK CS admissions counselors.",
    heroDescription: "The counselor reviews existing evidence, then asks focused questions about the student's actions and thinking. Unconfirmed details stay blank.",
    stepIntro: "01 · Start a case", introDescription: "Select a UK undergraduate CS programme, then upload a structured, de-identified CV. Each case uses one experience and three follow-up questions.",
    programLabel: "Target programme", programNote: "Programme requirements are extracted from the original project and have not been manually verified. General UCAS guidance is shown separately.", guidanceTitle: "General UCAS writing guidance", guidanceScope: "This is UK-wide guidance, not a preference unique to the selected university.", guidanceLink: "Open UCAS source",
    cvLabel: "Structured CV (.json)", chooseFile: "Choose JSON file", noFile: "No file selected", downloadSample: "Download a sample CV and edit it for your test cases", startUploaded: "Start with uploaded CV", start: "Try the built-in demo",
    uploadNote: "Use fictional or de-identified data. The file is sent only to this local server and kept in memory until restart.",
    fileMissing: "Choose a JSON file first.", fileLarge: "The CV file must be 25 KB or smaller.", fileInvalid: "The file is not valid JSON.",
    stepInterview: "02 · Focused interview", answerLabel: "Student's own words",
    answerPlaceholder: "Be specific: What happened? What did you do? Why did you choose that approach?",
    submit: "Submit answer", skip: "Skip this question", finishEarly: "Create story card now", recordTitle: "Six-part evidence record",
    stepResult: "03 · Counselor review", restart: "Start again",
    footer: "Course prototype. Upload only fictional or de-identified CVs. Programme requirements have not been manually verified. This is neither an admissions decision nor a completed personal statement.",
    empty: "Not yet provided", unanswered: "Unanswered / unconfirmed", evidenceTitle: "Confirmed student evidence",
    angleTitle: "Writing angle (for counselor confirmation)", gapsTitle: "Programme requirements and gaps to verify",
    modeLive: "Generated by DashScope; the evidence quote was checked verbatim", modeDemo: "Local template demo; no model was called",
    gapNote: "Knowledge-base status: human_verified=false. This comparison is a demonstration; the counselor should check the official programme page.",
    noGaps: "The structured grades trigger no gap against the selected sample requirements. Verify the official page and full entry conditions.", subjectsPrefix: "Predicted subjects: ",
    sourceLink: "Open the official programme page", quotePrefix: "Verbatim evidence: ", missingPrefix: "Still needed: ",
    notice: "The writing angle is a discussion prompt for the counselor and student. Do not present unconfirmed ideas as the student's experiences. The programme requirements have not been manually verified.",
    needsEvidence: "More evidence needed", reviewable: "Ready for counselor review", completeness: "evidence elements complete",
    student: "Fictional student A (Year 12, A-Level)", experience: "School mathematics modelling club and city-level student competition",
    questionProblem: "What specific difficulty did you personally encounter in this experience? Where did you get stuck?",
    questionSolution: "How did you address that difficulty? What did you personally do, and why did you choose that approach?",
    questionReflection: "What new questions or reflections did this experience raise about your intended subject? It is fine to say that none came to mind.",
    gapMath: (actual, expected) => `Predicted Mathematics grade: ${actual || "unknown"}. Sample requirement: ${expected}.`,
    gapScience: "The current profile does not list any of the science subjects named in the sample requirement.",
    usage: (input, output) => `This call used ${input} input tokens and ${output} output tokens.`,
    labels: {process:"Actions and role",knowledge:"Knowledge and skills",problem:"Difficulty",solution:"Approach",reflection:"Personal reflection",outcome:"Outcome"},
    facts: {"担任数据整理与图表制作":"Responsible for organising data and creating charts","数据整理、图表制作":"Data organisation and chart creation","市级三等奖":"Third prize at city level"},
    errorFallback: "The request failed. Check the server log."
  }
};

let language;
try { language = localStorage.getItem("academic-compass-language") === "zh" ? "zh" : "en"; }
catch { language = "en"; }
let current = null;
let lastBrief = null;

function t(key) { return copy[language][key]; }
function clear(node) { node.replaceChildren(); }
function text(tag, content, className="") {
  const node = document.createElement(tag);
  node.textContent = content;
  if (className) node.className = className;
  return node;
}
function displayFact(value) { return value ? (current?.is_demo ? (t("facts")[value] || value) : value) : t("unanswered"); }
function displayCaseText(value, key) { return current?.is_demo ? t(key) : value; }
function displayMissing(label) {
  const key = elementKeys.find(item => copy.zh.labels[item] === label);
  return key ? t("labels")[key] : label;
}
function errorMessage(error) {
  const message = String(error.message || error);
  if (language === "zh") return message;
  if (message.includes("请输入回答")) return "Enter an answer or click Skip this question.";
  if (message.includes("最多 1500")) return "An answer can contain at most 1,500 characters.";
  if (message.includes("会话已失效")) return "This session has expired. Start again.";
  if (message.includes("DASHSCOPE_API_KEY")) return "Live mode needs a DASHSCOPE_API_KEY.";
  if (message.includes("CV 必须包含 student")) return "The CV must contain a student object.";
  if (message.includes("student.experience 必须是对象")) return "student.experience must be an object.";
  if (message.includes("student.subjects 必须是")) return "student.subjects must be a list of at most 20 items.";
  if (message.includes("经历至少")) return "The experience needs a role, skill, or output as traceable evidence.";
  if (message.includes("predicted 需为")) return "A predicted grade must be A*, A, B, C, D, or E.";
  if (message.includes("必须是最多 10 项")) return "Skills and outputs must be lists of at most 10 items.";
  if (message.includes("不能为空")) return `${message.split(" ")[0]} is required.`;
  if (message.includes("必须是文字")) return `${message.split(" ")[0]} must be text.`;
  if (message.includes("必须是对象")) return "Each subject must be an object with name and predicted grade.";
  if (message.includes("最多")) return "A CV field exceeds its length limit.";
  if (message.includes("模型引用未出现在学生证据中")) return "The model cited evidence that the student did not provide. Its suggestion was blocked.";
  if (message.includes("模型") || message.includes("请求")) return t("errorFallback");
  return message;
}
function showError(error) { $("error").textContent = error ? errorMessage(error) : ""; }

async function api(path, body) {
  const response = await fetch(path, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body)});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || t("errorFallback"));
  return data;
}

function updateStaticCopy() {
  document.documentElement.lang = language === "en" ? "en" : "zh-CN";
  for (const node of document.querySelectorAll("[data-i18n]")) node.textContent = t(node.dataset.i18n);
  for (const node of document.querySelectorAll("[data-i18n-placeholder]")) node.placeholder = t(node.dataset.i18nPlaceholder);
  $("languageToggle").textContent = language === "en" ? "中文" : "English";
  $("languageToggle").setAttribute("aria-label", language === "en" ? "Switch to Chinese" : "Switch to English");
  updateFileName();
}
function updateFileName() { $("cvFileName").textContent = $("cvFile").files[0]?.name || t("noFile"); }

function renderRecord(values, sources) {
  const root = $("record"); clear(root);
  for (const key of elementKeys) {
    const row = text("div", "", "row");
    row.append(text("b", t("labels")[key]), text("span", values[key] ? displayFact(values[key]) : t("empty")));
    if (sources[key]) row.append(text("small", sources[key], "source"));
    root.append(row);
  }
}

function renderInterview(data, resetAnswer=true) {
  current = data;
  $("intro").classList.add("hidden");
  $("result").classList.add("hidden");
  $("interview").classList.remove("hidden");
  showError(null);
  if (resetAnswer) $("answer").value = "";
  $("progress").textContent = `${data.round}/3`;
  $("caseSummary").textContent = `${displayCaseText(data.student, "student")} | ${displayCaseText(data.experience, "experience")} | ${data.programme.university} ${data.programme.name}`;
  const subjectText = data.subjects.map(item => `${item.name} ${item.predicted}`).join(", ");
  if (subjectText) $("caseSummary").append(text("p", t("subjectsPrefix") + subjectText, "muted"));
  renderRecord(data.values, data.sources);
  if (data.question) {
    $("question").textContent = language === "zh" ? data.question.text : data.question.text_en;
    if (resetAnswer) $("answer").focus();
  } else if (resetAnswer) finish();
}

function renderBrief(data) {
  lastBrief = data;
  $("interview").classList.add("hidden");
  $("result").classList.remove("hidden");
  const root = $("resultContent"); clear(root);
  const status = data.status === "可供顾问审阅" ? t("reviewable") : t("needsEvidence");
  root.append(text("h2", displayCaseText(data.experience, "experience")), text("span", `${status} · ${data.completeness} ${t("completeness")}`, "badge"));
  if (data.subjects.length) root.append(text("p", t("subjectsPrefix") + data.subjects.map(item => `${item.name} ${item.predicted}`).join(", "), "muted"));
  root.append(text("p", t("notice"), "notice"));

  const evidence = text("section", "", "block");
  evidence.append(text("h2", t("evidenceTitle")));
  for (const item of data.evidence) {
    const row = text("div", "", "row");
    row.append(text("b", t("labels")[item.element]), text("span", displayFact(item.text)));
    if (item.source) row.append(text("small", item.source, "source"));
    evidence.append(row);
  }
  root.append(evidence);

  const guidance = text("section", "", "block");
  guidance.append(text("h2", t("guidanceTitle")), text("p", language === "zh" ? data.writing_guidance.question_zh : data.writing_guidance.question), text("p", language === "zh" ? data.writing_guidance.focus_zh : data.writing_guidance.focus, "muted"), text("small", t("guidanceScope"), "notice"));
  const guidanceLink = text("a", t("guidanceLink"));
  guidanceLink.href = data.writing_guidance.source_url;
  guidanceLink.target = "_blank";
  guidanceLink.rel = "noopener noreferrer";
  guidance.append(guidanceLink);
  root.append(guidance);

  const angle = text("section", "", "block");
  angle.append(text("h2", t("angleTitle")));
  angle.append(text("p", data.suggestion[language === "en" ? "angle_en" : "angle_zh"]));
  angle.append(text("blockquote", `${t("quotePrefix")}${data.suggestion.evidence_quote}`, "quote"));
  angle.append(text("small", data.suggestion.mode === "live_model" ? t("modeLive") : t("modeDemo"), "muted"));
  root.append(angle);

  const gaps = text("section", "", "block"); gaps.append(text("h2", t("gapsTitle")));
  if (!data.gaps.length) gaps.append(text("p", t("noGaps")));
  for (const item of data.gaps) {
    const content = item.kind === "math_grade" ? t("gapMath")(item.actual, item.expected) : t("gapScience");
    gaps.append(text("p", content));
  }
  gaps.append(text("small", t("gapNote"), "muted"));
  const link = text("a", t("sourceLink"));
  link.href = data.programme.source_url; link.target = "_blank"; link.rel = "noopener noreferrer";
  const linkRow = text("p", ""); linkRow.append(link); gaps.append(linkRow); root.append(gaps);
  if (data.missing.length) root.append(text("p", t("missingPrefix") + data.missing.map(displayMissing).join(language === "en" ? ", " : "、"), "notice"));
  if (data.model_usage) root.append(text("small", t("usage")(data.model_usage.prompt_tokens || 0, data.model_usage.completion_tokens || 0), "muted"));
}

async function finish() {
  try {
    showError(null); $("finishEarly").disabled = true; $("submit").disabled = true;
    const data = await api("/api/finish", {session_id:current.session_id});
    renderBrief(data);
  } catch (error) { showError(error); }
  finally { $("finishEarly").disabled = false; $("submit").disabled = false; }
}
async function sendAnswer(answer) {
  try {
    showError(null); $("submit").disabled = true; $("skip").disabled = true;
    renderInterview(await api("/api/answer", {session_id:current.session_id, answer}));
  } catch (error) { showError(error); }
  finally { $("submit").disabled = false; $("skip").disabled = false; }
}

$("languageToggle").onclick = () => {
  language = language === "zh" ? "en" : "zh";
  try { localStorage.setItem("academic-compass-language", language); } catch {}
  updateStaticCopy();
  if (lastBrief && !$("result").classList.contains("hidden")) renderBrief(lastBrief);
  else if (current && !$("interview").classList.contains("hidden")) renderInterview(current, false);
};
$("start").onclick = async () => { try { lastBrief = null; renderInterview(await api("/api/start", {program_id:$("programSelect").value})); } catch(error) { showError(error); } };
$("cvFile").onchange = updateFileName;
$("startUploaded").onclick = async () => {
  try {
    showError(null);
    const file = $("cvFile").files[0];
    if (!file) throw new Error(t("fileMissing"));
    if (file.size > 25_000) throw new Error(t("fileLarge"));
    let cv;
    try { cv = JSON.parse(await file.text()); }
    catch { throw new Error(t("fileInvalid")); }
    $("startUploaded").disabled = true;
    lastBrief = null;
    renderInterview(await api("/api/start", {cv, program_id:$("programSelect").value}));
  } catch (error) { showError(error); }
  finally { $("startUploaded").disabled = false; }
};
$("submit").onclick = () => sendAnswer($("answer").value);
$("skip").onclick = () => sendAnswer("[跳过]");
$("finishEarly").onclick = finish;
$("restart").onclick = () => {
  current = null; lastBrief = null; showError(null);
  $("result").classList.add("hidden");
  $("interview").classList.add("hidden");
  $("intro").classList.remove("hidden");
};
updateStaticCopy();
fetch("/api/programmes").then(response => response.json()).then(data => {
  clear($("programSelect"));
  for (const programme of data.programmes) {
    const option = document.createElement("option");
    option.value = programme.id;
    option.textContent = `${programme.university} · ${programme.name}`;
    $("programSelect").append(option);
  }
}).catch(showError);
